# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- pwsh: |
    cd .\.build
    .\CodeFormatter.ps1
  displayName: "Code Formatting Script"

- pwsh: |
    cd .\.build
    .\Build.ps1
  displayName: "Build Script"

- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'CSS Exchange Code Sign'
    FolderPath: 'D:\a\1\s\dist'
    Pattern: '*.ps1'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
        {
          "keyCode": "CP-230012",
          "operationSetCode": "SigntoolSign",
          "parameters": [
            {
              "parameterName": "OpusName",
              "parameterValue": "CSS Exchange"
            },
            {
              "parameterName": "OpusInfo",
              "parameterValue": "https://github.com/microsoft/CSS-Exchange"
            },
            {
              "parameterName": "PageHash",
              "parameterValue": "/NPH"
            },
            {
              "parameterName": "FileDigest",
              "parameterValue": "/fd sha256"
            },
            {
              "parameterName": "TimeStamp",
              "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
            }
          ],
          "toolName": "signtool.exe",
          "toolVersion": "6.2.9304.0"
        }
      ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'
